<?php

declare(strict_types=1);

/**
 * One-off dev seeder: inserts 30 varied test machines (mixed statuses,
 * featured flags, currencies, negotiable prices, and a few intentionally
 * minimal rows with only name/brand/category) so the admin panel and public
 * catalog have real data to click through. Images point at /uploads/seed-src-*
 * files, which are copies of the existing stock photos under
 * frontend/public/images — not run through the upload pipeline, just placed
 * directly since this is test data, not real uploads.
 *
 * Run with: docker compose exec php php database/seed_machines.php
 */

require_once __DIR__ . '/../src/Config/Env.php';
require_once __DIR__ . '/../src/Config/Database.php';
require_once __DIR__ . '/../src/Repositories/MachineRepository.php';
require_once __DIR__ . '/../src/Support/Slugify.php';

Env::load(__DIR__ . '/../.env');

function uniqueSlug(string $base, array &$usedInThisRun): string
{
    $slug = Slugify::make($base);
    $candidate = $slug;
    $suffix = 2;
    while (MachineRepository::slugExists($candidate) || isset($usedInThisRun[$candidate])) {
        $candidate = $slug . '-' . $suffix;
        $suffix++;
    }
    $usedInThisRun[$candidate] = true;
    return $candidate;
}

function img(string $n): string
{
    return '/uploads/seed-src-' . $n;
}

$machines = [
    [
        'name' => 'Bobcat S650 მინი დამტვირთველი', 'name_en' => 'Bobcat S650 Skid-Steer Loader',
        'brand' => 'Bobcat', 'category' => 'მინი დამტვირთველები', 'model' => 'S650', 'year' => 2023,
        'condition_status' => 'new', 'status' => 'available', 'featured' => true,
        'price' => 45000, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => 'Bobcat / 4 cyl. turbo დიზელი', 'power_hp' => 74, 'operating_weight_kg' => 3400,
        'load_capacity_kg' => 1200, 'lift_height_m' => null, 'working_hours' => 50,
        'fuel_type' => 'დიზელი', 'cabin' => 'დახურული, გათბობა/კონდიცირებით', 'warranty' => '2 წელი / 2000 სთ',
        'description' => 'ახალი Bobcat S650 მინი დამტვირთველი, იდეალურია სამშენებლო და სასოფლო სამუშაოებისთვის. მაღალი ტვირთამწეობა და კომფორტული კაბინა.',
        'description_en' => 'Brand-new Bobcat S650 skid-steer loader, ideal for construction and agricultural work. High lift capacity and a comfortable enclosed cab.',
        'specs' => [['label' => 'ჰიდრავლიკური ხარჯი', 'value' => '98 ლ/წთ']],
        'main_image' => img('10.webp'), 'images' => [img('18.jpg'), img('01.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Bobcat T590 გუმტრეკიანი დამტვირთველი', 'name_en' => 'Bobcat T590 Compact Track Loader',
        'brand' => 'Bobcat', 'category' => 'მინი დამტვირთველები', 'model' => 'T590', 'year' => 2022,
        'condition_status' => 'used', 'status' => 'available', 'featured' => false,
        'price' => 38000, 'currency' => 'USD', 'price_negotiable' => true,
        'engine' => 'Bobcat / 4 cyl. დიზელი', 'power_hp' => 68, 'operating_weight_kg' => 3742,
        'load_capacity_kg' => 1050, 'lift_height_m' => null, 'working_hours' => 1850,
        'fuel_type' => 'დიზელი', 'cabin' => 'დახურული', 'warranty' => '6 თვე',
        'description' => 'მეორადი, კარგ მდგომარეობაში მყოფი გუმტრეკიანი დამტვირთველი. რეგულარულად ტექმომსახურებული.',
        'description_en' => 'Used compact track loader in good condition, regularly serviced.',
        'specs' => [], 'main_image' => img('18.jpg'), 'images' => [img('10.webp'), img('04.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Kubota KX080 ექსკავატორი', 'name_en' => 'Kubota KX080 Excavator',
        'brand' => 'Kubota', 'category' => 'ექსკავატორები', 'model' => 'KX080-4', 'year' => 2023,
        'condition_status' => 'new', 'status' => 'available', 'featured' => true,
        'price' => 62000, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => 'Kubota V3307 / 4 cyl. დიზელი', 'power_hp' => 65.4, 'operating_weight_kg' => 8200,
        'load_capacity_kg' => null, 'lift_height_m' => 6.1, 'working_hours' => 20,
        'fuel_type' => 'დიზელი', 'cabin' => 'დახურული, კონდიცირებით', 'warranty' => '3 წელი / 3000 სთ',
        'description' => 'ახალი Kubota KX080 ჰიდრავლიკური ექსკავატორი — მაღალი წარმადობა და დაბალი საწვავის ხარჯვა.',
        'description_en' => 'New Kubota KX080 hydraulic excavator — high performance with low fuel consumption.',
        'specs' => [['label' => 'თხრის სიღრმე', 'value' => '4.4 მ'], ['label' => 'ბალთის ტევადობა', 'value' => '0.28 მ³']],
        'main_image' => img('14.jpg'), 'images' => [img('15.jpg'), img('16.jpg')],
        'meta_title' => 'Kubota KX080 ექსკავატორი იყიდება — ახალი | Intertechnics',
        'meta_description' => 'ახალი Kubota KX080 ჰიდრავლიკური ექსკავატორი საუკეთესო ფასად, გარანტიით და მიწოდებით თბილისში.',
    ],
    [
        'name' => 'Kubota U55 მინი ექსკავატორი', 'name_en' => 'Kubota U55 Mini Excavator',
        'brand' => 'Kubota', 'category' => 'ექსკავატორები', 'model' => 'U55-4', 'year' => 2021,
        'condition_status' => 'used', 'status' => 'available', 'featured' => false,
        'price' => 34000, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => 'Kubota / 3 cyl. დიზელი', 'power_hp' => 47.1, 'operating_weight_kg' => 5500,
        'load_capacity_kg' => null, 'lift_height_m' => 5.3, 'working_hours' => 3100,
        'fuel_type' => 'დიზელი', 'cabin' => 'დახურული', 'warranty' => null,
        'description' => 'საიმედო მეორადი მინი ექსკავატორი ვიწრო სამშენებლო მოედნებისთვის.',
        'description_en' => 'Reliable used mini excavator, well suited to tight job sites.',
        'specs' => [], 'main_image' => img('15.jpg'), 'images' => [img('14.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Kubota M9960 ტრაქტორი', 'name_en' => 'Kubota M9960 Tractor',
        'brand' => 'Kubota', 'category' => 'სასოფლო ტექნიკა', 'model' => 'M9960', 'year' => 2020,
        'condition_status' => 'used', 'status' => 'reserved', 'featured' => false,
        'price' => 41000, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => 'Kubota V3800 / 4 cyl. დიზელი', 'power_hp' => 95, 'operating_weight_kg' => 3800,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => 4200,
        'fuel_type' => 'დიზელი', 'cabin' => 'დახურული, კონდიცირებით', 'warranty' => null,
        'description' => 'მძლავრი სასოფლო-სამეურნეო ტრაქტორი, დაჯავშნილია მყიდველისთვის.',
        'description_en' => 'Powerful agricultural tractor, currently reserved for a buyer.',
        'specs' => [], 'main_image' => img('16.jpg'), 'images' => [img('14.jpg'), img('03.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'AMMANN ASC110 ვიბროსატკეპნი', 'name_en' => 'AMMANN ASC110 Vibratory Roller',
        'brand' => 'AMMANN', 'category' => 'ვიბროსატკეპნები', 'model' => 'ASC110', 'year' => 2023,
        'condition_status' => 'new', 'status' => 'available', 'featured' => true,
        'price' => null, 'currency' => 'USD', 'price_negotiable' => true,
        'engine' => 'Deutz / 4 cyl. დიზელი', 'power_hp' => 130, 'operating_weight_kg' => 11000,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => 10,
        'fuel_type' => 'დიზელი', 'cabin' => 'დახურული, ROPS/FOPS', 'warranty' => '1 წელი',
        'description' => 'ახალი AMMANN ASC110 გზის სატკეპნი — ფასი შეთანხმებით, დაგვიკავშირდით დეტალებისთვის.',
        'description_en' => 'Brand-new AMMANN ASC110 road roller — price on request, contact us for details.',
        'specs' => [], 'main_image' => img('09.webp'), 'images' => [img('05.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'AMMANN ABG 2820 ასფალტის დამგები', 'name_en' => 'AMMANN ABG 2820 Asphalt Paver',
        'brand' => 'AMMANN', 'category' => 'ასფალტის დამგები მანქანები', 'model' => 'ABG 2820', 'year' => 2019,
        'condition_status' => 'used', 'status' => 'sold', 'featured' => false,
        'price' => 155000, 'currency' => 'EUR', 'price_negotiable' => false,
        'engine' => 'Deutz / 6 cyl. დიზელი', 'power_hp' => 129, 'operating_weight_kg' => 15500,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => 6100,
        'fuel_type' => 'დიზელი', 'cabin' => 'ღია, ტენტით', 'warranty' => null,
        'description' => 'გაყიდულია. ინახება საარქივოდ — მსგავსი მოდელის შეკვეთისთვის დაგვიკავშირდით.',
        'description_en' => 'Sold — kept for reference. Contact us to order a similar model.',
        'specs' => [], 'main_image' => img('09.webp'), 'images' => [img('06.jpg'), img('02.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Kaeser M57 კომპრესორი', 'name_en' => 'Kaeser M57 Compressor',
        'brand' => 'Kaeser', 'category' => 'კომპრესორები', 'model' => 'M57', 'year' => 2022,
        'condition_status' => 'new', 'status' => 'available', 'featured' => false,
        'price' => 18500, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => 'Kubota / დიზელი', 'power_hp' => 49, 'operating_weight_kg' => 1450,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => 15,
        'fuel_type' => 'დიზელი', 'cabin' => null, 'warranty' => '2 წელი',
        'description' => 'პორტატული სამშენებლო კომპრესორი, მუდმივი წნევით და დაბალი ხმაურით.',
        'description_en' => 'Portable construction air compressor with steady pressure and low noise.',
        'specs' => [['label' => 'ჰაერის ხარჯი', 'value' => '5.0 მ³/წთ']],
        'main_image' => img('13.jpg'), 'images' => [img('07.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Kaeser CSD 105 ხრახნიანი კომპრესორი', 'name_en' => 'Kaeser CSD 105 Screw Compressor',
        'brand' => 'Kaeser', 'category' => 'კომპრესორები', 'model' => 'CSD 105', 'year' => 2021,
        'condition_status' => 'used', 'status' => 'available', 'featured' => false,
        'price' => 15200, 'currency' => 'USD', 'price_negotiable' => true,
        'engine' => 'ელექტრო ძრავი', 'power_hp' => 75, 'operating_weight_kg' => 980,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => 9800,
        'fuel_type' => 'ელექტრო', 'cabin' => null, 'warranty' => null,
        'description' => 'სტაციონარული ხრახნიანი კომპრესორი საამქროსთვის.',
        'description_en' => 'Stationary screw compressor for workshop use.',
        'specs' => [], 'main_image' => img('13.jpg'), 'images' => [],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Putzmeister BSA 1409 ბეტონის ტუმბო', 'name_en' => 'Putzmeister BSA 1409 Concrete Pump',
        'brand' => 'Putzmeister', 'category' => 'ბეტონის ტუმბოები', 'model' => 'BSA 1409', 'year' => 2020,
        'condition_status' => 'used', 'status' => 'available', 'featured' => true,
        'price' => 98000, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => 'Deutz / დიზელი', 'power_hp' => 136, 'operating_weight_kg' => 5800,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => 2450,
        'fuel_type' => 'დიზელი', 'cabin' => null, 'warranty' => '1 წელი',
        'description' => 'სტაციონარული ბეტონის ტუმბო მაღალი წარმადობით, ხშირად გამოყენებული ობიექტებზე.',
        'description_en' => 'High-output stationary concrete pump, well suited for busy job sites.',
        'specs' => [['label' => 'წარმადობა', 'value' => '90 მ³/სთ']],
        'main_image' => img('17.jpg'), 'images' => [img('02.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Putzmeister M 36-4 საბუთი ტუმბო', 'name_en' => 'Putzmeister M 36-4 Boom Pump',
        'brand' => 'Putzmeister', 'category' => 'ბეტონის ტუმბოები', 'model' => 'M 36-4', 'year' => 2018,
        'condition_status' => 'used', 'status' => 'reserved', 'featured' => false,
        'price' => 210000, 'currency' => 'EUR', 'price_negotiable' => false,
        'engine' => 'საბაზო შასზე', 'power_hp' => null, 'operating_weight_kg' => 32000,
        'load_capacity_kg' => null, 'lift_height_m' => 36, 'working_hours' => 5100,
        'fuel_type' => 'დიზელი', 'cabin' => null, 'warranty' => null,
        'description' => '36-მეტრიანი საბუთი ბეტონის ტუმბო, დაჯავშნილია.',
        'description_en' => '36-metre truck-mounted boom concrete pump — currently reserved.',
        'specs' => [], 'main_image' => img('17.jpg'), 'images' => [img('06.jpg'), img('05.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'HBM Nobas MEGA 1250 ბეტონის ქარხანა', 'name_en' => 'HBM Nobas MEGA 1250 Batching Plant',
        'brand' => 'HBM Nobas', 'category' => 'ბეტონის ქარხნები', 'model' => 'MEGA 1250', 'year' => 2019,
        'condition_status' => 'used', 'status' => 'available', 'featured' => false,
        'price' => 145000, 'currency' => 'EUR', 'price_negotiable' => true,
        'engine' => null, 'power_hp' => null, 'operating_weight_kg' => null,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => null,
        'fuel_type' => 'ელექტრო', 'cabin' => null, 'warranty' => null,
        'description' => 'სტაციონარული ბეტონის საწარმოო კვანძი მაღალი საათური წარმადობით.',
        'description_en' => 'Stationary concrete batching plant with high hourly output.',
        'specs' => [['label' => 'წარმადობა', 'value' => '125 მ³/სთ'], ['label' => 'მიქსერის ტიპი', 'value' => 'ორლილვიანი']],
        'main_image' => img('11.jpg'), 'images' => [img('03.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'HBM Nobas COMPACT 30 მინი ბეტონის კვანძი', 'name_en' => 'HBM Nobas COMPACT 30 Mini Batching Plant',
        'brand' => 'HBM Nobas', 'category' => 'ბეტონის ქარხნები', 'model' => 'COMPACT 30', 'year' => 2022,
        'condition_status' => 'new', 'status' => 'available', 'featured' => false,
        'price' => 89000, 'currency' => 'EUR', 'price_negotiable' => false,
        'engine' => null, 'power_hp' => null, 'operating_weight_kg' => null,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => 0,
        'fuel_type' => 'ელექტრო', 'cabin' => null, 'warranty' => '2 წელი',
        'description' => 'კომპაქტური მობილური ბეტონის კვანძი მცირე და საშუალო ობიექტებისთვის.',
        'description_en' => 'Compact mobile batching plant for small and mid-sized sites.',
        'specs' => [['label' => 'წარმადობა', 'value' => '30 მ³/სთ']],
        'main_image' => img('11.jpg'), 'images' => [img('07.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'INS Makina INS-160 ასფალტის ქარხანა', 'name_en' => 'INS Makina INS-160 Asphalt Plant',
        'brand' => 'INS Makina', 'category' => 'ასფალტის ქარხნები', 'model' => 'INS-160', 'year' => 2021,
        'condition_status' => 'used', 'status' => 'available', 'featured' => true,
        'price' => 320000, 'currency' => 'EUR', 'price_negotiable' => false,
        'engine' => null, 'power_hp' => null, 'operating_weight_kg' => null,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => 8200,
        'fuel_type' => 'დიზელი/გაზი', 'cabin' => null, 'warranty' => null,
        'description' => 'სტაციონარული ასფალტის საწარმოო ქარხანა 160 ტ/სთ წარმადობით.',
        'description_en' => 'Stationary asphalt mixing plant rated at 160 t/h output.',
        'specs' => [['label' => 'წარმადობა', 'value' => '160 ტ/სთ'], ['label' => 'ბუნკერების რაოდენობა', 'value' => '4']],
        'main_image' => img('12.jpg'), 'images' => [img('02.jpg'), img('05.jpg')],
        'meta_title' => 'INS Makina INS-160 ასფალტის ქარხანა — მეორადი | Intertechnics',
        'meta_description' => 'INS Makina INS-160 ასფალტის საწარმოო ქარხანა საუკეთესო ფასად, გარანტიით და მიწოდებით თბილისში.',
    ],
    [
        'name' => 'Aliva-262 საშხეფი ბეტონის მანქანა', 'name_en' => 'Aliva-262 Shotcrete Machine',
        'brand' => 'Aliva', 'category' => 'საშხეფი ბეტონის მანქანები', 'model' => 'Aliva-262', 'year' => 2017,
        'condition_status' => 'used', 'status' => 'available', 'featured' => false,
        'price' => 55000, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => 'ელექტრო/პნევმატური', 'power_hp' => null, 'operating_weight_kg' => 1650,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => 3900,
        'fuel_type' => 'ელექტრო', 'cabin' => null, 'warranty' => null,
        'description' => 'როტორული საშხეფი მანქანა გვირაბებისა და ხერხემლის სამუშაოებისთვის.',
        'description_en' => 'Rotor-type shotcrete machine for tunnelling and support work.',
        'specs' => [], 'main_image' => img('08.jpg'), 'images' => [img('04.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Kmayco KM-100 გენერატორი', 'name_en' => 'Kmayco KM-100 Generator',
        'brand' => 'Kmayco', 'category' => 'გენერატორები', 'model' => 'KM-100', 'year' => 2023,
        'condition_status' => 'new', 'status' => 'available', 'featured' => false,
        'price' => 12500, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => 'Cummins / დიზელი', 'power_hp' => 134, 'operating_weight_kg' => 1350,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => 5,
        'fuel_type' => 'დიზელი', 'cabin' => 'ხმაურდაცული კონტეინერი', 'warranty' => '1 წელი',
        'description' => 'დიზელგენერატორი 100 კვტ სიმძლავრით, ავტომატური ჩართვის სისტემით.',
        'description_en' => '100 kW diesel generator with automatic transfer switch support.',
        'specs' => [['label' => 'სიმძლავრე', 'value' => '100 კვტ']],
        'main_image' => img('01.jpg'), 'images' => [img('03.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Kmayco KM-P50 სატუმბი სადგური', 'name_en' => 'Kmayco KM-P50 Pump Station',
        'brand' => 'Kmayco', 'category' => 'სატუმბი სადგურები', 'model' => 'KM-P50', 'year' => 2023,
        'condition_status' => 'new', 'status' => 'available', 'featured' => false,
        'price' => null, 'currency' => 'USD', 'price_negotiable' => true,
        'engine' => 'დიზელი', 'power_hp' => 50, 'operating_weight_kg' => 620,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => 0,
        'fuel_type' => 'დიზელი', 'cabin' => null, 'warranty' => '1 წელი',
        'description' => 'მობილური სატუმბი სადგური სამშენებლო ობიექტის წყალამოღებისთვის.',
        'description_en' => 'Mobile pump station for construction-site dewatering.',
        'specs' => [], 'main_image' => img('04.jpg'), 'images' => [],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Bobcat E35 მინი ექსკავატორი', 'name_en' => 'Bobcat E35 Mini Excavator',
        'brand' => 'Bobcat', 'category' => 'ექსკავატორები', 'model' => 'E35', 'year' => 2022,
        'condition_status' => 'used', 'status' => 'available', 'featured' => true,
        'price' => 42000, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => 'Kubota / 3 cyl. დიზელი', 'power_hp' => 24.8, 'operating_weight_kg' => 3660,
        'load_capacity_kg' => null, 'lift_height_m' => 4.9, 'working_hours' => 1200,
        'fuel_type' => 'დიზელი', 'cabin' => 'დახურული', 'warranty' => '6 თვე',
        'description' => 'კომპაქტური მინი ექსკავატორი შეზღუდულ სივრცეში სამუშაოდ.',
        'description_en' => 'Compact mini excavator built for tight, restricted work areas.',
        'specs' => [], 'main_image' => img('18.jpg'), 'images' => [img('10.webp'), img('01.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Bobcat 3400 სამუშაო ტრანსპორტი', 'name_en' => 'Bobcat 3400 Utility Vehicle',
        'brand' => 'Bobcat', 'category' => 'სამუშაო ტრანსპორტი', 'model' => '3400', 'year' => 2023,
        'condition_status' => 'new', 'status' => 'available', 'featured' => false,
        'price' => 24000, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => 'ბენზინი, 4 ცილინდრიანი', 'power_hp' => 55, 'operating_weight_kg' => 830,
        'load_capacity_kg' => 450, 'lift_height_m' => null, 'working_hours' => 5,
        'fuel_type' => 'ბენზინი', 'cabin' => 'ღია ROPS', 'warranty' => '1 წელი',
        'description' => 'ორადგილიანი სამუშაო ტრანსპორტი ფერმისა და სამშენებლო ობიექტისთვის.',
        'description_en' => 'Two-seat utility vehicle for farm and job-site use.',
        'specs' => [], 'main_image' => img('10.webp'), 'images' => [],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Kubota SVL75-3 ტრეკიანი დამტვირთველი', 'name_en' => 'Kubota SVL75-3 Track Loader',
        'brand' => 'Kubota', 'category' => 'მინი დამტვირთველები', 'model' => 'SVL75-3', 'year' => 2022,
        'condition_status' => 'new', 'status' => 'available', 'featured' => false,
        'price' => 58000, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => 'Kubota V3307 / დიზელი', 'power_hp' => 74.3, 'operating_weight_kg' => 4227,
        'load_capacity_kg' => 1497, 'lift_height_m' => null, 'working_hours' => 30,
        'fuel_type' => 'დიზელი', 'cabin' => 'დახურული, კონდიცირებით', 'warranty' => '2 წელი / 2000 სთ',
        'description' => 'მაღალი ტვირთამწეობის მქონე ტრეკიანი დამტვირთველი, კომფორტული საოპერატორო ადგილით.',
        'description_en' => 'High-capacity track loader with a comfortable operator station.',
        'specs' => [], 'main_image' => img('14.jpg'), 'images' => [img('16.jpg'), img('15.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'AMMANN ASC70 ვიბროსატკეპნი', 'name_en' => 'AMMANN ASC70 Vibratory Roller',
        'brand' => 'AMMANN', 'category' => 'ვიბროსატკეპნები', 'model' => 'ASC70', 'year' => 2020,
        'condition_status' => 'used', 'status' => 'sold', 'featured' => false,
        'price' => 21000, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => null, 'power_hp' => null, 'operating_weight_kg' => 7000,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => 3300,
        'fuel_type' => 'დიზელი', 'cabin' => null, 'warranty' => null,
        'description' => 'გაყიდულია — არქივში ინახება მსგავსი მოთხოვნებისთვის.',
        'description_en' => null,
        'specs' => [], 'main_image' => img('09.webp'), 'images' => [],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Kaeser Mobilair M100 კომპრესორი', 'name_en' => null,
        'brand' => 'Kaeser', 'category' => 'კომპრესორები', 'model' => 'Mobilair M100', 'year' => 2019,
        'condition_status' => 'used', 'status' => 'available', 'featured' => false,
        'price' => null, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => null, 'power_hp' => null, 'operating_weight_kg' => null,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => null,
        'fuel_type' => null, 'cabin' => null, 'warranty' => null,
        'description' => null, 'description_en' => null,
        'specs' => [], 'main_image' => img('13.jpg'), 'images' => [],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Putzmeister P 715 ტრეილერული ტუმბო', 'name_en' => null,
        'brand' => 'Putzmeister', 'category' => 'ბეტონის ტუმბოები', 'model' => 'P 715', 'year' => 2016,
        'condition_status' => 'used', 'status' => 'available', 'featured' => false,
        'price' => null, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => null, 'power_hp' => null, 'operating_weight_kg' => null,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => null,
        'fuel_type' => null, 'cabin' => null, 'warranty' => null,
        'description' => null, 'description_en' => null,
        'specs' => [], 'main_image' => img('17.jpg'), 'images' => [],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'HBM Nobas SILO 60T ცემენტის სილოსი', 'name_en' => null,
        'brand' => 'HBM Nobas', 'category' => 'ბეტონის ქარხნები', 'model' => 'SILO 60T', 'year' => 2020,
        'condition_status' => 'used', 'status' => 'available', 'featured' => false,
        'price' => null, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => null, 'power_hp' => null, 'operating_weight_kg' => null,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => null,
        'fuel_type' => null, 'cabin' => null, 'warranty' => null,
        'description' => null, 'description_en' => null,
        'specs' => [], 'main_image' => img('11.jpg'), 'images' => [],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'INS Makina მობილური ასფალტის ქარხანა', 'name_en' => null,
        'brand' => 'INS Makina', 'category' => 'ასფალტის ქარხნები', 'model' => 'INS-MOBILE-100', 'year' => 2018,
        'condition_status' => 'used', 'status' => 'reserved', 'featured' => false,
        'price' => null, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => null, 'power_hp' => null, 'operating_weight_kg' => null,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => null,
        'fuel_type' => null, 'cabin' => null, 'warranty' => null,
        'description' => null, 'description_en' => null,
        'specs' => [], 'main_image' => img('12.jpg'), 'images' => [],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Aliva-246 საშხეფი ბეტონის მანქანა', 'name_en' => 'Aliva-246 Shotcrete Machine',
        'brand' => 'Aliva', 'category' => 'საშხეფი ბეტონის მანქანები', 'model' => 'Aliva-246', 'year' => 2015,
        'condition_status' => 'used', 'status' => 'available', 'featured' => false,
        'price' => 31000, 'currency' => 'USD', 'price_negotiable' => true,
        'engine' => 'პნევმატური', 'power_hp' => null, 'operating_weight_kg' => 980,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => 5600,
        'fuel_type' => 'პნევმატური', 'cabin' => null, 'warranty' => null,
        'description' => 'როტორული საშხეფი მანქანა, სრული აქსესუარებით — შლანგები, სახრახნისები, სათადარიგო ნაწილები.',
        'description_en' => 'Rotor-type shotcrete machine, complete with hoses, nozzles and spare parts.',
        'specs' => [
            ['label' => 'მაქს. ზომა შემავსებელი', 'value' => '16 მმ'],
            ['label' => 'წარმადობა', 'value' => '6 მ³/სთ'],
            ['label' => 'შლანგის სიგრძე', 'value' => '40 მ'],
        ],
        'main_image' => img('08.jpg'), 'images' => [img('07.jpg'), img('02.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Kmayco KM-W200 შედუღების აგრეგატი', 'name_en' => 'Kmayco KM-W200 Welding Generator',
        'brand' => 'Kmayco', 'category' => 'სამშენებლო აღჭურვილობა', 'model' => 'KM-W200', 'year' => 2023,
        'condition_status' => 'new', 'status' => 'available', 'featured' => false,
        'price' => 9800, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => 'დიზელი', 'power_hp' => 20, 'operating_weight_kg' => 410,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => 2,
        'fuel_type' => 'დიზელი', 'cabin' => null, 'warranty' => '1 წელი',
        'description' => 'შედუღების დიზელაგრეგატი მობილური სამშენებლო სამუშაოებისთვის.',
        'description_en' => 'Diesel welding generator for mobile construction work.',
        'specs' => [['label' => 'შედუღების დენი', 'value' => '200A']],
        'main_image' => img('06.jpg'), 'images' => [img('03.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Bobcat B730 ექსკავატორ-დამტვირთველი', 'name_en' => 'Bobcat B730 Backhoe Loader',
        'brand' => 'Bobcat', 'category' => 'ექსკავატორ-დამტვირთველები', 'model' => 'B730', 'year' => 2021,
        'condition_status' => 'used', 'status' => 'available', 'featured' => true,
        'price' => 47000, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => 'Bobcat / 4 cyl. დიზელი', 'power_hp' => 108, 'operating_weight_kg' => 8200,
        'load_capacity_kg' => 1400, 'lift_height_m' => 4.2, 'working_hours' => 2200,
        'fuel_type' => 'დიზელი', 'cabin' => 'დახურული, კონდიცირებით', 'warranty' => '6 თვე',
        'description' => 'ორმხრივი ექსკავატორ-დამტვირთველი — წინ სატვირთი ციცხვი, უკან სატყორცნი მკლავი.',
        'description_en' => 'Versatile backhoe loader — front loading bucket, rear digging arm.',
        'specs' => [], 'main_image' => img('18.jpg'), 'images' => [img('10.webp'), img('04.jpg'), img('01.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'Kubota KX057-4 მინი ექსკავატორი', 'name_en' => 'Kubota KX057-4 Mini Excavator',
        'brand' => 'Kubota', 'category' => 'ექსკავატორები', 'model' => 'KX057-4', 'year' => 2023,
        'condition_status' => 'new', 'status' => 'available', 'featured' => false,
        'price' => 39500, 'currency' => 'USD', 'price_negotiable' => false,
        'engine' => 'Kubota / 3 cyl. დიზელი', 'power_hp' => 42.3, 'operating_weight_kg' => 5595,
        'load_capacity_kg' => null, 'lift_height_m' => 5.5, 'working_hours' => 8,
        'fuel_type' => 'დიზელი', 'cabin' => 'დახურული', 'warranty' => '3 წელი / 3000 სთ',
        'description' => 'ახალი მინი ექსკავატორი ზუსტი ჰიდრავლიკური მართვით.',
        'description_en' => 'New mini excavator with precise hydraulic controls.',
        'specs' => [], 'main_image' => img('15.jpg'), 'images' => [img('14.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
    [
        'name' => 'AMMANN AFW 150 ასფალტის ქარხანა', 'name_en' => 'AMMANN AFW 150 Universal Asphalt Plant',
        'brand' => 'AMMANN', 'category' => 'ასფალტის ქარხნები', 'model' => 'AFW 150 Universal', 'year' => 2017,
        'condition_status' => 'used', 'status' => 'available', 'featured' => false,
        'price' => 275000, 'currency' => 'EUR', 'price_negotiable' => true,
        'engine' => null, 'power_hp' => null, 'operating_weight_kg' => null,
        'load_capacity_kg' => null, 'lift_height_m' => null, 'working_hours' => 11400,
        'fuel_type' => 'დიზელი/გაზი', 'cabin' => null, 'warranty' => null,
        'description' => 'უნივერსალური ტიპის ასფალტის საწარმოო ქარხანა 150 ტ/სთ წარმადობით, დემონტაჟი და ტრანსპორტირება შესაძლებელია.',
        'description_en' => 'Universal-type asphalt mixing plant rated at 150 t/h, dismantling and transport available.',
        'specs' => [['label' => 'წარმადობა', 'value' => '150 ტ/სთ']],
        'main_image' => img('09.webp'), 'images' => [img('06.jpg'), img('05.jpg'), img('02.jpg')],
        'meta_title' => null, 'meta_description' => null,
    ],
];

$usedInThisRun = [];
$created = 0;
foreach ($machines as $m) {
    $m['slug'] = uniqueSlug($m['name'], $usedInThisRun);
    MachineRepository::create($m);
    $created++;
    echo "Created: {$m['name']}\n";
}

echo "\nDone. {$created} machines inserted.\n";
